webkit-classic: enchant -> enchant2
ERROR: Nothing PROVIDES 'enchant' (but /home/hains/openpli-oe-core/meta-qviart/recipes-webkit/webkit/webkit-classic.bb
DEPENDS on or otherwise requires it). Close matches:
  enca
  enchant2
  weechat